name: Deploy wheel to PyPI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  main_build:
    runs-on: ubuntu-24.04
    name: Sequential build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Main build
        id: build
        uses: ./.github/actions
